// This file was generated by gir (https://github.com/gtk-rs/gir @ b16d610)
// from gir-files (https://github.com/gtk-rs/gir-files @ 2bd095f2)
// DO NOT EDIT

#[cfg(any(not(doc), doctest))]
use std::process;

#[cfg(all(not(doctest), doc))]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(any(not(doc), doctest))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        let _ = eprintln!("{}", s);
        process::exit(1);
    }
}
