// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use gst_rtsp_server_sys;

glib_wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct RTSPAddress(Boxed<gst_rtsp_server_sys::GstRTSPAddress>);

    match fn {
        copy => |ptr| gst_rtsp_server_sys::gst_rtsp_address_copy(mut_override(ptr)),
        free => |ptr| gst_rtsp_server_sys::gst_rtsp_address_free(ptr),
        get_type => || gst_rtsp_server_sys::gst_rtsp_address_get_type(),
    }
}

unsafe impl Send for RTSPAddress {}
