// This file was generated by gir (d933f9a+) from gir-files (???)
// DO NOT EDIT

use DiscovererStreamInfo;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DiscovererAudioInfo(Object<ffi::GstDiscovererAudioInfo>): DiscovererStreamInfo;

    match fn {
        get_type => || ffi::gst_discoverer_audio_info_get_type(),
    }
}

unsafe impl Send for DiscovererAudioInfo {}
unsafe impl Sync for DiscovererAudioInfo {}

pub trait DiscovererAudioInfoExt {
    fn get_bitrate(&self) -> u32;

    fn get_channels(&self) -> u32;

    fn get_depth(&self) -> u32;

    fn get_language(&self) -> Option<String>;

    fn get_max_bitrate(&self) -> u32;

    fn get_sample_rate(&self) -> u32;
}

impl<O: IsA<DiscovererAudioInfo>> DiscovererAudioInfoExt for O {
    fn get_bitrate(&self) -> u32 {
        unsafe {
            ffi::gst_discoverer_audio_info_get_bitrate(self.to_glib_none().0)
        }
    }

    fn get_channels(&self) -> u32 {
        unsafe {
            ffi::gst_discoverer_audio_info_get_channels(self.to_glib_none().0)
        }
    }

    fn get_depth(&self) -> u32 {
        unsafe {
            ffi::gst_discoverer_audio_info_get_depth(self.to_glib_none().0)
        }
    }

    fn get_language(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::gst_discoverer_audio_info_get_language(self.to_glib_none().0))
        }
    }

    fn get_max_bitrate(&self) -> u32 {
        unsafe {
            ffi::gst_discoverer_audio_info_get_max_bitrate(self.to_glib_none().0)
        }
    }

    fn get_sample_rate(&self) -> u32 {
        unsafe {
            ffi::gst_discoverer_audio_info_get_sample_rate(self.to_glib_none().0)
        }
    }
}
