// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git)
// DO NOT EDIT

#![cfg(unix)]

use gstreamer_allocators_sys::*;
use std::env;
use std::error::Error;
use std::ffi::OsString;
use std::mem::{align_of, size_of};
use std::path::Path;
use std::process::{Command, Stdio};
use std::str;
use tempfile::Builder;

static PACKAGES: &[&str] = &["gstreamer-allocators-1.0"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Self, Box<dyn Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        // For _Generic
        args.push("-std=c11".to_owned());
        // For %z support in printf when using MinGW.
        args.push("-D__USE_MINGW_ANSI_STDIO".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Self { args })
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {cmd:?} failed, {status}").into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<dyn Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{name} {err}").into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<dyn Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let pkg_config = env::var_os("PKG_CONFIG").unwrap_or_else(|| OsString::from("pkg-config"));
    let mut cmd = Command::new(pkg_config);
    cmd.arg("--cflags");
    cmd.args(packages);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn summary(&self) -> String {
        format!("{} passed; {} failed", self.passed, self.failed)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let mut c_constants: Vec<(String, String)> = Vec::new();

    for l in get_c_output("constant").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing ';' separator");
        c_constants.push((name.to_owned(), value.to_owned()));
    }

    let mut results = Results::default();

    for ((rust_name, rust_value), (c_name, c_value)) in
        RUST_CONSTANTS.iter().zip(c_constants.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_value != c_value {
            results.record_failed();
            eprintln!(
                "Constant value mismatch for {rust_name}\nRust: {rust_value:?}\nC:    {c_value:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let mut c_layouts = Vec::new();

    for l in get_c_output("layout").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing first ';' separator");
        let (size, alignment) = value.split_once(';').expect("Missing second ';' separator");
        let size = size.parse().expect("Failed to parse size");
        let alignment = alignment.parse().expect("Failed to parse alignment");
        c_layouts.push((name.to_owned(), Layout { size, alignment }));
    }

    let mut results = Results::default();

    for ((rust_name, rust_layout), (c_name, c_layout)) in RUST_LAYOUTS.iter().zip(c_layouts.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_layout != c_layout {
            results.record_failed();
            eprintln!("Layout mismatch for {rust_name}\nRust: {rust_layout:?}\nC:    {c_layout:?}",);
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

fn get_c_output(name: &str) -> Result<String, Box<dyn Error>> {
    let tmpdir = Builder::new().prefix("abi").tempdir()?;
    let exe = tmpdir.path().join(name);
    let c_file = Path::new("tests").join(name).with_extension("c");

    let cc = Compiler::new().expect("configured compiler");
    cc.compile(&c_file, &exe)?;

    let mut cmd = Command::new(exe);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }

    Ok(String::from_utf8(out.stdout)?)
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    (
        "GstAHardwareBufferFormat",
        Layout {
            size: size_of::<GstAHardwareBufferFormat>(),
            alignment: align_of::<GstAHardwareBufferFormat>(),
        },
    ),
    (
        "GstDRMDumbAllocatorClass",
        Layout {
            size: size_of::<GstDRMDumbAllocatorClass>(),
            alignment: align_of::<GstDRMDumbAllocatorClass>(),
        },
    ),
    (
        "GstDmaBufAllocator",
        Layout {
            size: size_of::<GstDmaBufAllocator>(),
            alignment: align_of::<GstDmaBufAllocator>(),
        },
    ),
    (
        "GstDmaBufAllocatorClass",
        Layout {
            size: size_of::<GstDmaBufAllocatorClass>(),
            alignment: align_of::<GstDmaBufAllocatorClass>(),
        },
    ),
    (
        "GstFdAllocator",
        Layout {
            size: size_of::<GstFdAllocator>(),
            alignment: align_of::<GstFdAllocator>(),
        },
    ),
    (
        "GstFdAllocatorClass",
        Layout {
            size: size_of::<GstFdAllocatorClass>(),
            alignment: align_of::<GstFdAllocatorClass>(),
        },
    ),
    (
        "GstFdMemoryFlags",
        Layout {
            size: size_of::<GstFdMemoryFlags>(),
            alignment: align_of::<GstFdMemoryFlags>(),
        },
    ),
    (
        "GstPhysMemoryAllocatorInterface",
        Layout {
            size: size_of::<GstPhysMemoryAllocatorInterface>(),
            alignment: align_of::<GstPhysMemoryAllocatorInterface>(),
        },
    ),
    (
        "GstShmAllocator",
        Layout {
            size: size_of::<GstShmAllocator>(),
            alignment: align_of::<GstShmAllocator>(),
        },
    ),
    (
        "GstShmAllocatorClass",
        Layout {
            size: size_of::<GstShmAllocatorClass>(),
            alignment: align_of::<GstShmAllocatorClass>(),
        },
    ),
    (
        "GstUdmabufAllocatorClass",
        Layout {
            size: size_of::<GstUdmabufAllocatorClass>(),
            alignment: align_of::<GstUdmabufAllocatorClass>(),
        },
    ),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_B10G10R10A2_UNORM", "67"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_B10G10R10X2_UNORM", "68"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_BLOB", "33"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_D16_UNORM", "48"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_D24_UNORM", "49"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_D24_UNORM_S8_UINT", "50"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_D32_FLOAT", "51"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_D32_FLOAT_S8_UINT", "52"),
    (
        "(gint) GST_AHARDWARE_BUFFER_FORMAT_R10G10B10A10_UNORM",
        "59",
    ),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R10G10B10A2_UNORM", "43"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R12G12B12A12_UINT", "65"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R12G12_UINT", "63"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R12_UINT", "61"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R14G14B14A14_UINT", "66"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R14G14_UINT", "64"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R14_UINT", "62"),
    (
        "(gint) GST_AHARDWARE_BUFFER_FORMAT_R16G16B16A16_FLOAT",
        "22",
    ),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R16G16_UINT", "58"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R16_UINT", "57"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R5G6B5_UNORM", "4"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R8G8B8A8_UNORM", "1"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R8G8B8X8_UNORM", "2"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R8G8B8_UNORM", "3"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_R8_UNORM", "56"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_S8_UINT", "53"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_Y8Cb8Cr8_420", "35"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_YCbCr_P010", "54"),
    ("(gint) GST_AHARDWARE_BUFFER_FORMAT_YCbCr_P210", "60"),
    ("GST_ALLOCATOR_DMABUF", "dmabuf"),
    ("GST_ALLOCATOR_FD", "fd"),
    ("GST_ALLOCATOR_SHM", "shm"),
    ("GST_ALLOCATOR_UDMABUF", "udmabuf"),
    (
        "GST_CAPS_FEATURE_MEMORY_AHARDWAREBUFFER",
        "memory:AHardwareBuffer",
    ),
    ("GST_CAPS_FEATURE_MEMORY_DMABUF", "memory:DMABuf"),
    ("(guint) GST_FD_MEMORY_FLAG_DONT_CLOSE", "4"),
    ("(guint) GST_FD_MEMORY_FLAG_KEEP_MAPPED", "1"),
    ("(guint) GST_FD_MEMORY_FLAG_MAP_PRIVATE", "2"),
    ("(guint) GST_FD_MEMORY_FLAG_NONE", "0"),
];
