// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%.6f", \
                    double: "%.6f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_B10G10R10A2_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_B10G10R10X2_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_BLOB);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_D16_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_D24_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_D24_UNORM_S8_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_D32_FLOAT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_D32_FLOAT_S8_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R10G10B10A10_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R10G10B10A2_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R12G12B12A12_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R12G12_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R12_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R14G14B14A14_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R14G14_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R14_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R16G16B16A16_FLOAT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R16G16_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R16_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R5G6B5_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R8G8B8A8_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R8G8B8X8_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R8G8B8_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_R8_UNORM);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_S8_UINT);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_Y8Cb8Cr8_420);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_YCbCr_P010);
    PRINT_CONSTANT((gint) GST_AHARDWARE_BUFFER_FORMAT_YCbCr_P210);
    PRINT_CONSTANT(GST_ALLOCATOR_DMABUF);
    PRINT_CONSTANT(GST_ALLOCATOR_FD);
    PRINT_CONSTANT(GST_ALLOCATOR_SHM);
    PRINT_CONSTANT(GST_ALLOCATOR_UDMABUF);
    PRINT_CONSTANT(GST_CAPS_FEATURE_MEMORY_AHARDWAREBUFFER);
    PRINT_CONSTANT(GST_CAPS_FEATURE_MEMORY_DMABUF);
    PRINT_CONSTANT((guint) GST_FD_MEMORY_FLAG_DONT_CLOSE);
    PRINT_CONSTANT((guint) GST_FD_MEMORY_FLAG_KEEP_MAPPED);
    PRINT_CONSTANT((guint) GST_FD_MEMORY_FLAG_MAP_PRIVATE);
    PRINT_CONSTANT((guint) GST_FD_MEMORY_FLAG_NONE);
    return 0;
}
