// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git)
// DO NOT EDIT

mod gl_display_egl;
pub use self::gl_display_egl::GLDisplayEGL;

pub(crate) mod traits {
    pub use super::gl_display_egl::GLDisplayEGLExt;
}
