// Generated by gir (https://github.com/gtk-rs/gir @ 72e79f7)
// from gir-files (https://github.com/gtk-rs/gir-files @ 7d95377)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git @ 208138a)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GstHarness", sizeof(GstHarness), alignof(GstHarness));
    printf("%s;%zu;%zu\n", "GstTestClock", sizeof(GstTestClock), alignof(GstTestClock));
    printf("%s;%zu;%zu\n", "GstTestClockClass", sizeof(GstTestClockClass), alignof(GstTestClockClass));
    return 0;
}
