// Generated by gir (https://github.com/gtk-rs/gir @ a3709a9f9d37)
// from gir-files (https://github.com/gtk-rs/gir-files @ b827978e7d18)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git @ 0220d4948268)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GstGLDisplayEGL", sizeof(GstGLDisplayEGL), alignof(GstGLDisplayEGL));
    printf("%s;%zu;%zu\n", "GstGLDisplayEGLClass", sizeof(GstGLDisplayEGLClass), alignof(GstGLDisplayEGLClass));
    return 0;
}
