// Generated by gir (https://github.com/gtk-rs/gir @ 74b6e47217b7)
// from gir-files (https://github.com/gtk-rs/gir-files @ 9e945716ad4c)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git @ d031d210fe4e)
// DO NOT EDIT

#[cfg(not(feature = "dox"))]
use std::process;

#[cfg(feature = "dox")]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(feature = "dox"))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={}", s);
        process::exit(1);
    }
}
